### ISSUE TITLE
Mr. G thinks there's an item before him if he's currently holding one in Waiter tutorial

### ISSUE THREAD

**Issue by Timmon26** [godotneers/programming-video#1]
Got stumped on the first Waiter challenge and did some testing. Turns out Mr. G always thinks there's an item before him if he's currently holding one.
I thought my code might be bad (and it might still be), so I wrote a simpler script to make sure. See below. Makes it difficult to include checks for items to pick up in loops. Unless debugging this is part of the tutorial, but that seems above my pay grade at the moment.

```gdscript
extends SteppingRobot

func turn_around():
	turn_right()
	turn_right()

func what_should_i_do():

	for step:int in 6:
		if is_item_before_me == true:
			say("There's an item before me, I'm going to grab it")
			pick_up_item()
			turn_around()
		elif i_have_an_item_in_hand == true:
			if tile_color_before_me == "LightBlue":
				say ("here's a blue tile, I'll drop my item here")
				drop_item()
				turn_around()
		else: step_forward()
		
		
# Code used to test the phantom item bug
#	for step:int in 10:
#		if is_item_before_me == true:
#			say("I see an item")
#			pick_up_item()
#		else: step_forward()
	
	pass
```

**Comment by derkork** [comment]
You have indeed found a bug! There is a lot of internal code going on which plays the animations and everything when you do a `step_forward` or `pick_up_item` and the code for picking up the item didn't properly remove the item from the world so `is_item_before_me` would still see it. I'll push a fix for this. Thanks a lot for taking the time to debug/report this!
